name: Pipe Line

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Step 1
      run: |
        echo 'Step 1 Executed'
        exit 1
  job_two:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: Step 2
       run: |
         echo 'Step 2 Executed'
