name: Pipe Line

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      VARIABLE_ONE: value_one

    steps:
    - uses: actions/checkout@v4
    - name: Step 1
      run: |
        echo 'Step 1 Executed'
        cp intended_command_fail
    - name: Step 2
      run: |
        echo 'Step 2 Executed'
    - name: Step 3
      run: |
        echo 'Step 3 Executed'
